version: '3'

services:
  php:
    image: php:7.3.26-cli-alpine
    container_name: php
    depends_on:
      - db
    entrypoint: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/usr/src/myapp
      - ./.env.docker:/usr/src/myapp/.env
    working_dir: /usr/src/myapp
    ports:
      - '8000:8000'
    networks:
      - main
  db:
    container_name: db
    image: postgres:13.1-alpine
    command: 'postgres -c max_connections=5 -c shared_buffers=64MB'
    restart: always
    ports:
      - '5432:5432'
    #volumes:
    #  - ./.docker/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - main

networks:
  main:
    driver: 'bridge'
